name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Pip and deps
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Display python
      run: python -c "import sys; print(sys.version)"

    - name: Testing
      run: pytest

    
      